NorwoodAndBrixtonFoodbank/nbf-website

package-lock.json, package.json, src/components/Icons/CongestionChargeAppliesIcon.tsx, src/components/Icons/FeetIcon.tsx, src/components/Icons/FlagIcon.tsx, src/components/Icons/Icon.tsx, src/components/Icons/Icons.cy.tsx, src/components/Icons/PhoneIcon.tsx, src/components/Icons/SpeechBubbleIcon.tsx, src/components/Icons/TruckIcon.tsx
Implemented icon components for Flag, Phone, Truck, Congestion Charge Applies, Feet, and Speech Bubble. Each icon has the appropriate on-hover text titles, and have been tested using unit tests for each.
- can run `npm run fix` to try and fix as any mistakes automatically as possible!
=> VFB-4 Add components for Icons

next.config.js
This flag should be enabled by default as far as I can tell although setting it appears to fix the issue. Using non experimental-flag workarounds don't appear to work without completely opting out of client-side routing. Can others also test if this actually fixes things?
=> Fix navigation in the navbar

cypress.config.ts, package.json
`npm run open:cypress` was querying the wrong port, apologies! forgot I hardcoded it in the config :eyes:
this should work!
=> Fix Cypress port in config

src/components/DataInput/DataInput.cy.tsx, src/components/DataInput/FreeFormTextInput.tsx
This is to add error message functionality to FreeFormTextInput in DataInput component. The colour should be red and the message will be shown underneath the box. We added a test case in cypress.
=> VFB-8: Add error message functionality to freeform text input

src/app/calendar/page.tsx, src/components/Calendar/Calendar.cy.tsx, src/components/Calendar/Calendar.tsx, src/components/Calendar/Modal.tsx, src/components/DataViewer/DataViewer.tsx
The modal will not display "Description: " if the description fed in is undefined. Also, the calendar will display days as inclusive for full day events
=> VFB-2 Improve modal display and calendar for full-day event 

cypress/e2e/accessibility.cy.ts
Change accessibility test because it was overridden when add-clients was merged in main
=> Change accessibility test for navbar

src/app/global_styles.tsx
Hard coded MuiInputLabel to only disable color transition but remain all other motions
=> VFB-16 Partially disable colour transition on input

cypress/e2e/accessibility.cy.ts, src/app/calendar/ParcelCalendar.tsx, src/app/calendar/page.tsx, src/app/calendar/parcelCalendarFunctions.ts, src/components/Calendar/Calendar.cy.tsx, src/components/Calendar/Calendar.tsx, src/components/Calendar/EventModal.tsx, src/components/Title/Title.tsx
Improved Calendar and Calendar Page display so that it is fully responsive in both mobile and desktop (do test it out!)
Added features - clicking a day will navigate to that day in day view
Refactored Calendar Page client fetching with SQL join
=> VFB 2 Reformat Calendar and Calendar Page

cypress/e2e/auth.cy.ts, src/app/login/page.tsx, src/components/LoginPanel.tsx, src/components/NavBar/NavigationBar.tsx
1. Centered the login component
2. Put title inside the login panel
3. Wrap a NoSsr to suppress hydration error
4. Made a LoginDependent component which will only show the children when not in the login page. Used to hide the navbar elements when we are in the login page.
=> VFB-17 Restyle login component

src/app/auth.tsx
Normal login and logout times even locally were exceeding 500ms and causes an unpleasant white flash as themes update when not using client side routing so I've extended the timeout
=> Extend auth timeout

src/app/clients/ActionBar.cy.tsx, src/app/clients/AddParcelsButton.tsx, src/app/clients/ClientsPage.cy.tsx, src/app/clients/ClientsPage.tsx, src/app/clients/getClientsTableData.ts, src/app/clients/getExpandedClientDetails.ts, src/app/layout.tsx
Currently, when the client's row in the popup is clicked, it will redirect to clients/[id] but there is no page for that yet. 
Also had to make some minor changes for the ActionBar which uses parcel.collectionDatetime but that wasn't in ClientsTableRow.
=> Add Parcels button on Clients Page

cypress/e2e/themes.cy.ts
Theme tests were failing locally due to having dark mode as the system preference, then the system clicking and switching to light mode but testing to dark mode. Have changed this/ will change any other failing tests on main if they exist.
=> Fixing tests on Main

cypress/support/commands.ts
Instead of reading the title of the page to determine what page we're on, read from the url.
=> Fix Login Retry in Tests

src/components/PdfButton/PdfButton.cy.tsx, src/components/PdfButton/PdfButton.tsx
Removed the time dependency in the file name of pdf test. This makes the test not flaky when it takes more than a second to run.
=> Removed time dependency from pdf test

package-lock.json, src/components/Tables/Table.tsx
Update react-data-table-component 
=> VFB-88: Upgrade react-data-table-component to v7.6.2

.github/workflows/deploy-database.yml
I've tried using `pg_dump` and `pg_restore` but the tools didn't quite work as expected - the connection was somehow refused even though the credentials were definitely correct. The somewhat easier / safer option (since Supbase db has a bunch of hidden tables for their housekeeping) would be to use Supabase CLI to reset the dev database, including the seed data. This is easily extendable to the prod pipeline. The only difference for prod is that we want both the "deploy" job and the "reset" job to be manual steps.
- Add a job to reset the dev database data
I have checked that:
Once this is merged, I still need to check that we can run this individual job manually without triggering the deploy job. If this works as expected, we can create similar jobs to deploy / reset database on prod. I …
=> VFB-108: Add job to reset dev database data

.github/workflows/checks.yml, package.json
- Add SUPABASE_LOCAL_SERVICE_ROLE_KEY and SUPABASE_LOCAL_ANON_KEY to secrets to be used in the pipeline
- When running the e2e tests in the pipeline, start a local Supabase instance and create necessary users / bucket.
- Modify the e2e tests to target the local Supabase instance
- Split the `Check linting and run component tests` job into `Check linting` and `Run component tests`
=> VFB-110: Test starting supabase locally

src/app/parcels/EventTable.tsx, src/app/parcels/ExpandedParcelDetails.tsx, src/app/parcels/ParcelsPage.cy.tsx, src/app/parcels/getExpandedParcelDetails.ts
Added paginated table of events to the bottom of the parcel details modal. Columns are "event", which displays the event name following by paranthesised event data, if any, and "timestamp", which displays the timestamp in DD/MM/YYYY, HH:MM:SS format.
| ![image](https://github.com/VauxhallFoodbank/vauxhall-foodbank/assets/138508884/5eba12b3-a572-4e07-a4e8-50f3108defbc) | ![image](https://github.com/VauxhallFoodbank/vauxhall-foodbank/assets/138508884/e7f83098-27f8-42ed-8111-3f771cf22cbe) |
=> VFB-35: parcel modal statuses

src/app/parcels/ExpandedParcelDetails.tsx, src/app/parcels/ExpandedParcelDetailsFallback.tsx
This PR is a fix to VFB-35-Parcel-modal-statuses. 
Fixed event ordering to be by date/time, with most recent at the top. Also, added an empty event table to the fallback option for the parcel details modal.
| ![image](https://github.com/VauxhallFoodbank/vauxhall-foodbank/assets/138508884/ff02f3d8-d010-48c1-8eaf-64c7e0f38707) | ![image](https://github.com/VauxhallFoodbank/vauxhall-foodbank/assets/138508884/1da1e7b9-e256-4b30-87e4-d76413aa81ed) |
=> VFB-35: FIX - event ordering by date

.github/workflows/checks.yml, .github/workflows/verify-generated-database-types.yml
- Verify generated database types in the pipeline only when necessary
- Ignore changes in .github folder for `checks` workflow
=> NONE: Verify generated database types in the pipeline only when necessary

.eslintrc.json, src/app/admin/AdminPage.tsx, src/app/admin/common/passwordConfig.tsx, src/app/admin/createCollectionCentre/CreateCollectionCentreForm.tsx, src/app/admin/createUser/CreateUserForm.tsx, src/app/clients/form/ClientForm.tsx, src/app/clients/form/formSections/NumberChildrenCard.tsx, src/app/parcels/ActionBar/ActionsModal.tsx, src/app/parcels/ActionBar/Statuses.tsx, src/app/parcels/ActionBar/StatusesModal.tsx, src/app/parcels/form/ParcelForm.tsx, src/app/themes.cy.tsx, src/components/DataInput/DropdownListInput.tsx, src/components/DataInput/RadioGroupInput.tsx, src/components/DataViewer/DataViewerFallback.tsx, src/pdf/DayOverview/DayOverviewPdf.tsx, src/pdf/DriverOverview/DriverOverviewPdf.tsx, src/pdf/ShippingLabels/ShippingLabelsPdf.tsx, src/pdf/ShoppingList/ShoppingListPdf.tsx
- Add eslint rules to disallow array index as key
- If using array index is reasonable - each item could potentially contain the same info, and we don't expect the data to change on the page - then add `eslint-ignore`. This was particularly the case for some of hte PDF elements where none of the fields are inherently unique.
=> VFB-99: Add eslint rules to disallow array index as key

.github/workflows/checks.yml, .github/workflows/deploy-database.yml, .github/workflows/deploy-dev-database.yml, .github/workflows/deploy-prod-database.yml, .github/workflows/verify-generated-database-types.yml
- Add migration and reset steps for prod
- This is triggered by pushes to the main branch
- We should now target the `dev` branch when creating pull requests. When we're ready to promote the recent changes to prod, we can move the `main` branch up to the desired commit (or the latest `dev` commit), and that deploys the website and triggers the migration step.
- Add `prod` and `dev` GitHub environments. Workflow jobs for `prod` require approval from myself or @stonelink (config is found [here](https://github.com/VauxhallFoodbank/vauxhall-foodbank/settings/environments))
=> VFB-99: Add migration and reset steps for prod

src/app/parcels/ActionBar/Statuses.tsx, src/app/parcels/ParcelsPage.tsx
Sorting by last status in the parcel table results in rows ordered to be consistent with workflow - eg packed => ready to dispatch => delivered. Previously, sorting by last status had no effect except to revert any other sorts.
|![image](https://github.com/VauxhallFoodbank/vauxhall-foodbank/assets/138508884/fd2dbc28-af45-4b3f-b2ad-72feb52b3531)![image](https://github.com/VauxhallFoodbank/vauxhall-foodbank/assets/138508884/77a80011-656b-4aca-843e-34926fc05ccc)|![image](https://github.com/VauxhallFoodbank/vauxhall-foodbank/assets/138508884/3b1f6352-947e-40b7-b5e7-7998e737bd21)![image](https://github.com/VauxhallFoodbank/vauxhall-foodbank/assets/138508884/c8727cb8-9d76-41a7-9160-3dbb570848a3)|
- Will also be automatically checked on …
=> Vfb 40 sort by status

src/app/lists/ListDataview.tsx, src/app/lists/ListsPage.tsx, src/components/Calendar/Calendar.tsx
The login of onSwapRows has been updated to use the listOfIngridients function as props to update the row_order value of listsData
=> VFB 66 - onSwapRows amended to directly update the row order

package-lock.json, package.json, src/logger/logger.ts, src/server/serverConfig.ts
- Configure Winston so that we can log to CloudWatch and to the local console.
- Any logs at or above "warning" level will be sent to CloudWatch
- Any logs at or above "info" level will be printed to console - with colors.
This is just the first part of the ticket to introduce logging into the website. Once this is merged, I can ask devs to add logs wherever is appropriate.
=> VFB-57: Introduce error logging

src/app/parcels/ActionBar/ActionsModal.tsx
In the delete parcel modal, the confirmation displayed "Parcels deleted" indiscriminate of how many parcels were deleted. Now it displays "Parcel deleted" if one was deleted and "Parcels deleted" if more than one was deleted.
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/1616be69-63ed-4590-bdb9-9a185d56d93b) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/26659025-80f4-4ae6-af19-61e027d47e17) |
=> VFB-74: Delete parcel action FIX

src/app/parcels/ActionBar/Actions.tsx, src/app/parcels/ActionBar/ActionsModal.tsx
- Add generate map under actions on parcels page
- Opens google maps in new tab with the selected parcels postcode in a circular pin
- Shows error message if no parcels are selected
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/70527083-df27-4feb-b858-3f0380ae8574) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/7c189277-b839-4a96-9096-6ee41f32ab9e) |
=> VFB-52: Add generate maps action in parcels page

src/app/parcels/ActionBar/ActionsModal.tsx
In the driver overview pdf modal, the date is now defaulted to today. Previously, there was no default value.
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/af5acd6c-2102-4b45-b712-36c2d8236fb5) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/be806e75-9000-49ca-b465-c335147b24ec) |
If you have made any changes to the database... nope
=> #158: Default date to today in driver overview pdf input

src/pdf/ShippingLabels/ShippingLabelsPdf.tsx
Reduce width of shipping label to 150mm from 200mm, and made delivery instructions text wrap on to the next row(s) if needed, so it doesn't get cut off.
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/1465fcff-02de-4c4e-9fe0-f9497ef28129) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/7cafa42b-6d3b-4a17-a3a2-c56377ebb564) |
If you have made any changes to the database... nope
=> #156: Reduce width of shipping label to 150mm from 200mm

src/app/clients/form/submitFormHelpers.ts
After pressing the submit button in the edit client modal, we now navigate to the respective updated client details modal, instead of navigating to the add parcel modal.
After clicking "submit" in the edit client modal...
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/cf587015-5bdf-49bb-88ac-6c7800901955) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/6c98ca1e-5f66-49bd-a613-5d006635ef20) |
If you have made any changes to the database... nope
=> VFB-145: Open client modal after editing client

cypress/e2e/auth.cy.ts, src/components/Modal/Modal.tsx, src/components/NavigationBar/NavigationBar.tsx, src/components/NavigationBar/SignOutButton.tsx
Added a confirmation modal when logout icon is clicked.
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/49fda7d0-eaa5-49eb-900f-d030ab616bea) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/6d9d1e53-43ae-44b9-973e-dc3123a04ad9) |
If you have made any changes to the database... No changes to database
=> 155:Logout-confirmation-modal

src/components/DataInput/CheckboxGroupPopup.tsx, src/components/Tables/Table.tsx
Fixed breaking accessibility test on parcels page:
- table didn't have the correct roles for its children when the loading symbol was displayed within the table
- there was a duplicate id "status-button"
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/f01ca48d-fc1e-4976-8a67-2bc46d79ecd1) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/8475d1f5-68b3-44fc-bd51-2f24f0d9c8f2) |
=> NONE: Fix accessibility issues in parcels page

src/app/clients/ClientsPage.tsx, src/app/clients/getClientsData.ts, src/app/errorClasses.ts, src/app/parcels/ParcelsPage.tsx, src/app/parcels/fetchParcelTableData.ts, src/components/Tables/Table.cy.tsx
Fixed stale fetch logic, that was supposed to ensure that the most recently sent request is the one which the data is set to, no matter if another request returns sooner. It wasn't working, now it is. Both parcels and clients page.
If you have made any changes to the database... nope
- Does this require resetting the deployed database? - NO
=> VFB-29: FIX request pagination

cypress/e2e/accessibility.cy.ts
Disabled "aria-allowed-attr" rule in light and dark mode for calendar page
=> NONE: Disable accessibility test for calendar

src/app/admin/common/UserRoleDropdownInput.tsx, src/app/clients/form/formSections/NumberChildrenCard.tsx, src/app/parcels/ActionBar/ActionsModal.tsx, src/app/parcels/form/formSections/CollectionCentreCard.tsx, src/app/parcels/form/formSections/PackingSlotsCard.tsx, src/components/DataInput/DataInput.cy.tsx, src/components/DataInput/DropdownListInput.tsx
Add labelId for select to correspond to select label for accessibility
=> VFB-165: Add label corresponding labelId to select for accessibility

docs/README.md, docs/supabase-realtime-reset.md, supabase/migrations/20240328103536_enable_realtime.sql
Enable realtime through migration.
I have checked
=> NONE: Enable realtime through migration

.github/workflows/checks.yml, .github/workflows/verify-generated-database-types.yml, src/app/auth/reset-password/route.ts, src/app/update-password/page.tsx
- Edit the password reset email to say that the link needs to be opened using the same machine and browser (change in Supabase)
- If the password reset link did not work as expected, we should display an error and explain that it did not succeed, and a likely reason why.
- If password reset is successful, direct user to / which should redirect to parcels page automatically (as the user is already signed in at this point)
| N/A | Example of how the error message is displayed ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/114006382/7606e009-0865-4094-b090-2e7f31be8902) |
If you have made any changes to the database... NA
=> #199 improve password reset flow

src/app/parcels/ActionBar/ActionAndStatusButtons.cy.tsx, src/app/parcels/ActionBar/ActionAndStatusButtons.tsx, src/app/parcels/ActionBar/ActionBar.tsx, src/app/parcels/ParcelsPage.tsx, src/app/parcels/parcelsTableFilters.ts, src/components/Form/formStyling.tsx
- Show the number of selected parcels on the parcels page
- Removed the empty container shown above the parcels page
- Clean up of ParcelsPage.tsx (see comments)
I've tested against the current dev website to spot check various filters to make sure the results are identical.
=> #197: Show number of parcels selected

.github/workflows/deploy-dev-database.yml, .github/workflows/deploy-dry-prod-database.yml, .github/workflows/deploy-prod-database.yml
Previously, the migration could only run if the new migration files are timestamped after the current latest migration file. We want to run all migration files that are not in in the current db instead.
=> NONE: Add include-all flag when deploying database

.snaplet/snaplet-client.d.ts, .snaplet/snaplet.d.ts, src/app/parcels/ParcelsPage.tsx, src/components/Tables/Table.tsx
Currently we have options to show up to 10, 15, 20, 25 or 30 items on the parcels page. This has been changed to show 10, 25, 50 or 100 parcels instead.
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/114006382/b162182c-924e-483e-83f9-babedfb1318f) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/114006382/48e598c8-1222-4c31-9eee-b73a354b82fe) |
If you have made any changes to the database... Nope
- Checkout your …
=> VFB-135: display up to 100 parcels

cypress/e2e/themes.cy.ts, src/app/themes.tsx, src/components/Tables/Table.tsx
- rows in dark mode are higher contrast
- hovered rows are light green in both modes
|![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/24893a0e-4e6a-4e9b-9514-ce6bbe60aafb)![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/0e30cc1e-2957-40d3-8b48-db305f624c7c)|![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/2ff443f4-f0cf-47dc-98a1-f9fc5953b663)![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/fce413d4-dec7-4561-9fa6-71e9b363d4a5)|
=> VFB-137-FIX: Higher contrast rows in dark and green on hover

src/app/admin/common/StyledDataGrid.tsx
Datagrids (websitre data table and packing slots) have green rows on hover.
=> VFB-137: FIX 2 - green hover on data grids

src/app/parcels/ParcelsPage.tsx, src/components/Tables/Table.tsx
Display 100 parcels by default
If you have made any changes to the database... NOPE
=> #241: Display 100 parcels by default

src/app/admin/collectionCentresTable/CollectionCentresTable.tsx, src/app/admin/createCollectionCentre/CreateCollectionCentreForm.tsx
- Remove delete function for collection centres
- Add audit log for when collection centre is added
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/c8487c2e-2401-4864-aca7-3744f5cb77e3) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/a83a959f-3309-4395-8354-9b7729942774) |
- Run `npx supabase migrations up …
=> VFB-193: Add audit log for collection centre add, remove delete function

src/app/admin/createCollectionCentre/CreateCollectionCentreForm.tsx
- Display error message and log id
- Remove throw error
=> VFB-193-fix: Display error message and logid instead of throw

.snaplet/snaplet-client.d.ts, .snaplet/snaplet.d.ts, src/databaseTypesFile.ts, src/server/adminInviteUser.ts, src/server/auditLog.ts, supabase/migrations/20240410114803_add_column_profile_id_to_audit_log_table.sql
- Add audit logs for when email invite is sent and when profile for user is created
- Add profile_id to audit log for new user_id
=> VFB-192: Add audit logs when an invite link is sent

.snaplet/snaplet-client.d.ts, .snaplet/snaplet.d.ts, README.md, cypress/e2e/admin/packingSlots.cy.ts, docs/e2e-testing.md, package.json, src/app/admin/packingSlotsTable/PackingSlotActions.ts, src/app/admin/packingSlotsTable/PackingSlotsTable.tsx, src/databaseTypesFile.ts, supabase/migrations/20240411144335_fix_admin_only_rls_policies.sql
- Add audit logs for adding and editing packing slots
- Fix RLS policies checking for admin access
- Add an e2e test for moving packing slots
=> VFB-194 VFB-195: Add audit logs for adding and editing packing slots and fix RLS policies checking for admin access

src/app/admin/websiteDataTable/WebsiteDataTable.tsx, src/app/admin/websiteDataTable/fetchWebsiteData.ts, src/server/auditLog.ts
- Add audit log when website data is updated
- Return error instead of throwing
- Handling error and display error message to user
=> VFB-196 Add audit logs when website data is edited

src/app/admin/AdminPage.tsx, src/app/admin/collectionCentresTable/CollectionCentresTable.tsx, src/app/admin/createCollectionCentre/CreateCollectionCentreForm.tsx, src/app/admin/page.tsx
- Collection centres table update automatically after adding a new centre
- Success message is displayed
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/b9ab676d-4435-48fe-b314-72448261a832) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/1cb270fe-cad0-4047-98b0-984bacc0e383) |
- Run `npx supabase migrations up …
=> VFB-200: Add subscription channel to collections centre table

src/app/parcels/form/ParcelForm.tsx
Fixed a bug where any new parcels were added with a date equal to the day before the packing date that was input by the user.
No DB changes.
=> VFB-199: Fixed bug where parcels were added one day before their packing date

src/app/admin/common/SuccessFailureAlert.tsx
- Removed refresh button from success message when user is deleted
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/e12c3f52-5434-49cc-b267-2f847b958f80) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/9cbab14a-ae80-47f7-be55-d2cd667a1423) |
- Run `npx supabase migrations up --include-all --local` to run all outstanding …
=> VFB-197 fix: Remove refresh button from alert

src/app/parcels/ActionBar/Statuses.tsx, src/app/parcels/ParcelsPage.cy.tsx, src/app/parcels/fetchParcelTableData.ts, src/app/parcels/getExpandedParcelDetails.ts, src/databaseTypesFile.ts, src/databaseUtils.ts, supabase/migrations/20240418083600_add_fk_to_status_order_table_from_events_table.sql, supabase/seed/seed.mts
- Fetch statuses from status_order table instead of predetermined list from front end.
=> VFB-158: Fetch statuses from database instead of from list

cypress/e2e/admin/inviteUser.cy.ts, src/app/admin/createUser/AccountDetails.tsx, src/app/admin/createUser/CreateUserForm.tsx, src/app/admin/createUser/UserDetailsCard.tsx, src/components/DataInput/FreeFormTextInput.tsx, src/components/Form/formFunctions.ts
- Make phone number optional when adding a user
- If the input is an empty string and the field isn't required, return no validation error.
If you have made any changes to the database... Nope
=> #242: Make phone number optional when adding a user

src/app/parcels/ParcelsPage.tsx
- Display null parcel statuses as empty string instead of none
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/e2b70486-e28c-4435-bae7-704b99f3cb68) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/dc9d389c-a08d-4a49-9c04-d8254c3950c2) |
- Run `npx supabase migrations up --include-all --local` to run all outstanding …
=> #179: Display null parcel statuses as empty string

src/app/parcels/ActionBar/ActionAndStatusBar.cy.tsx, src/app/parcels/ActionBar/ActionAndStatusBar.tsx, src/app/parcels/ActionBar/Statuses.tsx, src/app/parcels/ParcelsPage.tsx
Stop rounding new status times to the nearest minute when a parcel's status is updated via status or action modal. Thus fixed a bug where the new status of a parcel did not update (because there could be multiple latest statuses)
Also took the opportunity to simplify status/action components by removing the functionality where these components call setIsLoading(true) and setIsLoading(false) for the parcels page - this is not needed, as if the status updates, these lines are called in ParcelsPage because the realtime channel is triggered. and if the status does not update (ie, the parcel has statuses in the future or the action failed) there is no need to change isLoading.
No DB changes.
=> VFB-154/204 - Fix status not updating bug by making new status times exact

src/app/admin/usersTable/usersTableFilters.ts
Fixed a bug where users with first name and/or last name equal to null were not displayed in the users table in the admin page. The null first/last name are now displayed as empty strings/blank cells.
| After      |
|------------|
|![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/52c9c737-c6d1-4ca1-8e3f-f55e4d1626b4)![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/ea8f3276-d710-49ee-9e58-370c66489689)![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/bfe10ab9-6b59-42ac-b911-bb1499d5fe6c)|
No DB changes.
=> VFB-203: Show users with no name in users table

src/app/lists/ListDataview.tsx
Send an audit log when a list item is moved up or down.
Please note: I decided to only send an audit log for the list item that was clicked, so that we have one audit log per list item order change, to be consistent with packing slots. (Opposed to two audit logs, one for each list item that moves - the one that is clicked and the one that it swaps with).
No DB changes.
=> VFB-210: Audit log list order change

src/app/admin/auditLogTable/auditLogModal/auditLogModalRows/Parcel.tsx, src/app/admin/auditLogTable/auditLogModal/auditLogModalRows/Profile.tsx, src/app/admin/auditLogTable/fetchAuditLogData.ts, src/app/admin/auditLogTable/format.ts, src/app/admin/auditLogTable/sortFunctions.ts, src/app/admin/auditLogTable/types.ts, src/app/parcels/ActionBar/SelectedParcelsOverview.tsx, src/common/format.ts, src/databaseTypesFile.ts, supabase/migrations/20240430152259_add_actor_role_to_audit_log_plus.sql
Fix for VFB-205 Audit log modal.
- Fix profile name sort, which was showing an error in front end
- Display role of deleted users in both audit log row and modal
- Display NFA in parcel link within audit log modal if applicable
- Does this require resetting the deployed database? - NO
=> VFB-205: Fix profile name sort, display role of deleted users, display NFA in parcel link if applicable

README.md
First time users may need to log in to snaplet before running the post_checkout script, so added a hint to the readme for this.
=> Add hint to first time setup to log in to snaplet

src/app/admin/deleteUser/DeleteUserDialog.tsx, src/app/admin/manageUser/EditUserForm.tsx, src/app/admin/manageUser/ResetPasswordForm.tsx, src/app/admin/manageUser/UpdateUserProfile.ts, src/app/admin/page.tsx, src/app/admin/usersTable/UsersTable.tsx, src/app/admin/usersTable/getUsersData.ts, src/app/admin/usersTable/usersTableFilters.ts, src/databaseTypesFile.ts, supabase/migrations/20240430155721_rename_profiles_plus_to_users_plus_and_include_profile_id.sql
- Audit log editing a user - currently only role changes are possible in the front end but the audit log logic will extend to any changes.
- Also fixed a bug where when you change a users role to one that was not previously held by any user, the user disappears from the users table until refreshing. Fixed this by filtering by all user roles not just those held by users in the DB. 
- Does this require resetting the deployed database? - NO
- …
=> VFB-209: Audit log editing a user

src/components/Calendar/Calendar.tsx
* Set the calendar to use en-GB locale so that the date is formatted correctly (day/month).
* This also makes Monday the first day of the week
* Kept the times as 12h (this overrides the locale defaults)
* Also extracted the `eventTimeFormat` specification to apply to all views because this was duplicated
| ![image](https://private-user-images.githubusercontent.com/80202270/319672080-f42f37c8-79fb-4adf-99c8-e310d1a4d99f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDQ3NDYsIm5iZiI6MTcxNDY0NDQ0NiwicGF0aCI6Ii84MDIwMjI3MC8zMTk2NzIwODAtZjQyZjM3YzgtNzlmYi00YWRmLTk5YzgtZTMxMGQxYTRkOTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUF …
=> #232: Use en-GB locale for calendar

src/app/parcels/ActionBar/ActionModals/DriverOverviewModal.tsx, src/app/parcels/ActionBar/ActionModals/ShippingLabelModal.tsx
Disable submit button when creating driver overview pdf when driver name is blank.
(Followed approach in ShippingLabelModal)
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167985147/e6e1509b-fbab-4270-ab3c-b06f47deee88) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167985147/ca3354c3-94e8-41f0-8fe9-c845026b8a83) ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167985147/fe5a9433-a4c0-458a-bcd7-f6eeba2b293f) |
no db changes
=> #181: Driver name should be mandatory field

package.json, src/pdf/ShippingLabels/ShippingLabelsPdf.tsx
The shipping label shows Parcel instead of Label
| ![327413663-9436a69c-ccd1-4da8-91f2-71530b1399c1](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167894215/09de5aac-b665-4176-bb45-30d027ad2bdb) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167894215/46922cad-2140-48cd-b37a-8a5c092c87e7) |
- [x ] The ticket is up-to-date - Please document any deviations from the original approach if there is any.
- [x ] I have documented the testing steps for QA
- [x ] I have self-reviewed this PR
- [x ] Make sure you've verified it works via `npm run build` and `npm run start`
- [x ] Make sure you've fixed all linting problems with `npm run lint_fix`
- [x ] Make sure you've tested via `npm run test:e2e` …
=> #184: Changed Label to Parcel on shipping label

src/components/NavigationBar/NavigationBar.tsx
- Removed logout button on forgot password page
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167985277/449181f9-4774-4480-b76f-53cd47b4edb7) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167985277/223eb776-054a-4335-847f-b61a3284ac36) |
If you have made any changes to the database... (no changes made)
=> #208: Removed logout button on forgot password page

src/app/parcels/parcelsTableFilters.ts
- Entering a '?' in the search field for "Voucher" now shows all parcels with empty voucher fields
Without filtering (for reference):
|![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167985277/4237f3e2-530e-47ae-a45f-b6ec26fe933f)|![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167985277/d7c5388e-c364-4840-9de1-ea6072d75f9b)|
If you have made any changes to the database... (no changes)
=> #205: Question mark in voucher search field returns parcels with empty voucher fields

src/app/parcels/ActionBar/ActionModals/GenerateMapModal.tsx
* Removed duplicate postcodes
* Appended `//` to URL to avoid generating route
(Unable to reproduce the bug where the generation fails the first time.)
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167985147/327025db-ba3f-4cf3-9903-8136cdc86fd5) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167985147/7e76816a-c23d-4f08-86a3-5d9825df9189) |
no db changes
=> VFB-181: Remove duplicate postcodes from Google Map generation

supabase/migrations/20240513142439_change_rld_policy_for_status_order_table.sql
Changed rls policy for status order table to authenticated only
- [] The ticket is up-to-date - Please document any deviations from the original approach if there is any.
- Does this require resetting the deployed database? - NO (remove as appropriate)
=> VFB-168: Change policy for status order table to authenticated only
