.eslintrc.json, .github/pull_request_template.md, .gitignore, cypress.config.ts, cypress/support/commands.ts, next.config.js, package.json
Updated the ESLint to stop complaining at type annotations, improved the cypress `login` command and generally swept up a little bit! :smile:
- can run `npm run lint)fix` to try and fix as any mistakes automatically as possible!
=> Implement Quality of Life changes

package-lock.json, package.json, src/app/clients/page.tsx, src/components/DataViewer/DataViewer.cy.tsx, src/components/DataViewer/DataViewer.tsx, src/components/DataViewer/DataViewerWithButton.tsx, src/components/DataViewer/SampleDataViewerWithButton.tsx
We have created 3 files as follows:
1. DataViewer: contains the modal itself
2. DataViewerWithButton: contains the example for using the DataViewer component. This is also used in the cypress test so please do not remove this.
3. Cypress test file
=> VFB-3 Create modal to read JSON input

README.md, src/database_types_file.ts, src/supabase.ts
ran the auto generate command to generate some more types for you :)
=> Add lists table to schema

package-lock.json, package.json, src/app/clients/page.tsx, src/components/Tables/Table.cy.tsx, src/components/Tables/Table.tsx, src/components/Tables/TableFilterBar.tsx
Make a table component
Add demo in Client Page
Created cypress component test for table
=> VFB 1 - Create table component

cypress.config.ts, cypress/e2e/themes.cy.ts, package.json
this time I have tested it in PowerShell and it _should_ work... definitely wasn't using lazy Bash syntax!
=> Set the Cypress port properly

README.md, src/database_types_file.ts
instead of family_id, this now refers to client's primary key :)
=> Update types to reflect supabase table changes

src/app/global_styles.tsx, src/components/Form/formStyling.tsx
Fixes the styling issues we saw in retro (aside from the tooltip issue which I can't reproduce in dev or release mode)
=> Implement minor styling hotfixes

src/app/clients/ClientsPage.tsx
Clients/Add Button added to main clients page
=> Clients/Add Button added to main clients page

src/supabase.ts
Added Update Schema in supabase.ts
=> Add Update Schema

src/components/LoginPanel.tsx
From technical review, made the login component styling more consistent with the other components.
=> VFB-17 Make login component consistent

src/app/clients/ActionBar.cy.tsx, src/app/clients/ActionBar.tsx, src/app/clients/ActionBarModal.tsx, src/app/clients/ClientsPage.cy.tsx, src/app/clients/ClientsPage.tsx, src/app/clients/getClientsTableData.ts, src/app/clients/page.tsx, src/app/global_styles.tsx, src/components/NavBar/NavigationBar.tsx, src/components/Tables/Table.tsx
This implements the bar that allows the user to add events to the database when parcels are selected.
(no longer a draft)
=> VFB-20 Implement the status/action bar for the clients page

src/components/Calendar/Calendar.tsx
I have added button hovering feature and used Mui Paper for Calendar
=> VFB-2 Add button hovering feature and used Mui Paper for Calendar

src/app/lists/CommentBox.tsx, src/app/lists/ListDataview.tsx, src/app/lists/page.tsx, src/components/DataInput/FreeFormTextInput.tsx
Added a comment box on lists. This should fetch the current comment on the database, then allow the user to alter the comment and submit it. Also added is a reset comment feature.
=> VFB-28 Add comment box

src/components/DriverOverview/DriverOverview.tsx
Made small changes as I missed Tom's comment before.
=> VFB-10 Small Changes Driver Overview

src/components/Buttons/GeneralButtonParts.tsx, src/components/Buttons/LinkButton.tsx, src/components/Buttons/NavBarButton.tsx, src/components/Buttons/PopUpButton.tsx, src/components/Modal/Modal.tsx, src/components/NavBar/NavigationBar.tsx
NavBarButton - used in the navBar (changes styling for selected page)
LinkButton - a button that brings you to a different page 
PopUpButton - a button that opens a modal 
=> Add to button component

src/app/clients/ActionBar.tsx, src/app/clients/ActionBarModal.tsx
Edited the modal titles so they say the status instead that being inside the modal.
=> Edit Modal title

src/app/clients/add/submitFormHelpers.ts, src/pdf/ShoppingList/dataPreparation.ts
The extra information is now displayed on view clients page when updated.
=> View Clients Page - Fix Extra Information Displaying an empty string

src/components/LoginPanel.tsx
Spot that the text color is wrong - should be primary not main
=> VFB-17 Login Button Text Color

src/app/clients/ClientsPage.cy.tsx, src/app/clients/ClientsPage.tsx, src/app/clients/ExpandedClientDetails.tsx, src/app/clients/fetchDataFromServer.ts, src/app/clients/getClientsTableData.ts, src/app/clients/getExpandedClientDetails.ts, src/app/clients/page.tsx
server side function was using something which was being called from a client side page as well, so it was marked as client side (and a supabase client component client was being used) on the server, which doesn't work because cookies doesn't exist.
I reordered some functions and converted to a server to make it all work!
=> Fix clients page having no data

src/app/lists/CommentBox.tsx
I have completely reworked the functionality of add comment box in order to make sure it works as intended.
=> VFB 28 Add Comment Box after Technical Review

src/app/clients/ActionBar.cy.tsx, src/pdf/ShoppingList/ShoppingList.tsx
Added stuff to make actions in action bar pass tests:
1. A lot of intercepts to intercept all the fetching by ShoppingList PDF.
2. Make ShoppingListPDF not async cause cypress likes it that way
=> Fix action bar tests

src/app/parcels/add/formSections/CollectionDateCard.tsx, src/app/parcels/add/formSections/PackingDateCard.tsx, src/components/Form/formFunctions.ts
After Technical Review, added a past date error message.
=> VFB 21 Add Parcels Technical Review Changes

.eslintrc.json, src/app/admin/page.tsx, src/app/auth.tsx, src/app/clients/add/ClientForm.tsx, src/app/layout.tsx, src/app/roles.tsx, src/components/NavigationBar/NavigationBar.cy.tsx, src/components/NavigationBar/NavigationBar.tsx, src/middleware.ts
Added functionality to edit what pages are available to users based on their role. Also edited the nav bar based on this.
=> VFB-34 Change view for callers

README.md, src/app/errorClasses.ts, src/app/layout.tsx, src/app/parcels/ActionBar/Actions.tsx, src/app/parcels/ActionBar/ActionsModal.tsx, src/app/parcels/ActionBar/ActionsModalButton.tsx, src/app/parcels/ActionBar/Statuses.tsx, src/common/formatClientsData.ts, src/components/PdfButton/PdfButton.cy.tsx, src/pdf/ShippingLabels/ShippingLabels.tsx, src/pdf/ShoppingList/ShoppingList.tsx, src/pdf/ShoppingList/ShoppingListPdf.tsx, src/pdf/ShoppingList/getShoppingListData.ts, src/pdf/ShoppingList/shoppingListPdfDataProps.ts
=> Vfb 54 shopping list action

package-lock.json, src/app/auth/callback/route.ts, src/app/clients/form/submitFormHelpers.ts, src/components/NavigationBar/NavigationBar.cy.tsx
=> VFB-NONE: Run npm audit fix and correct any type issues

src/app/clients/getExpandedClientDetails.ts, src/app/parcels/ExpandedParcelDetailsFallback.tsx, src/app/parcels/ParcelsPage.cy.tsx, src/app/parcels/getExpandedParcelDetails.ts, src/components/DataViewer/DataViewer.tsx, src/components/DataViewer/DataViewerFallback.tsx, src/components/Modal/Modal.tsx, src/components/Modal/ModalFormStyles.ts
This is mostly tidying & simplifying the appearance of the two modals.
=> VFB-100: Simplify styling in Client and Parcel modals, and review fields

src/app/admin/page.tsx, src/app/calendar/page.tsx, src/app/clients/edit/[id]/page.tsx, src/app/parcels/add/[clientId]/page.tsx, src/supabaseServer.ts, src/supabaseUtils.ts
- Prompted by [this comment](https://softwiretech.atlassian.net/browse/VFB-63?focusedCommentId=313279)
- Create the Supabase server client with cookies at request time (See [here](https://github.com/vercel/next.js/issues/46356#issuecomment-1456680538))
=> VFB-NONE: Fix cookies build error

.github/workflows/deploy-backend.yml, .github/workflows/deploy-database.yml
=> VFB-98: Automatic deployment to deployed dev database

src/components/LoginPanel.tsx
- Replaced hardcoded route for redirect at login page to {baseUrl}/auth/callback
This will need to be checked through the deployed website***
=> Vfb 112 reset password link points to localhost 3000

src/app/admin/collectionCentresTable/CollectionCentresTable.tsx, src/app/admin/usersTable/UsersTable.tsx, src/app/clients/ClientParcelsTable.tsx, src/app/clients/ClientsPage.tsx, src/app/lists/ListDataview.tsx, src/app/parcels/ActionBar/ActionBar.cy.tsx, src/app/parcels/ActionBar/ActionBar.tsx, src/app/parcels/ActionBar/Actions.tsx, src/app/parcels/ActionBar/ActionsModal.tsx, src/app/parcels/ActionBar/ActionsModalButton.tsx, src/app/parcels/ActionBar/SelectedParcelsOverview.tsx, src/app/parcels/ActionBar/ShowParcels.tsx, src/app/parcels/ActionBar/Statuses.tsx, src/app/parcels/ActionBar/StatusesModal.tsx, src/app/parcels/EventTable.tsx, src/app/parcels/ParcelsPage.tsx, src/components/Tables/Table.cy.tsx, src/components/Tables/Table.tsx
Added action to allow parcels to be deleted. The delete action modal shows the parcel details and cancel/delete buttons. On "deletion", an event gets added with name "Request Deleted", but the parcel(s) remain in the database. However, parcels which have a "Request Deleted" event as their most recent event, are filtered out from the parcels table by default. This behaviour can be changed by the user.
| ![image](https://github.com/VauxhallFoodbank/vauxhall-foodbank/assets/138508884/eb6b2d60-2ad7-4a8c-95c8-7a8b6c92e3de)![image](https://github.com/VauxhallFoodbank/vauxhall-foodbank/assets/138508884/c12ead94-6d49-44d5-8cf7-519e2b52aa27)|![image](https://github.com/VauxhallFoodbank/vauxhall-foodbank/assets/138508884/dd759321-d0fd-4b49-997c …
=> Vfb 74 delete parcel action

README.md, src/components/Calendar/Calendar.tsx
Start and end time has been added to the weekly & daily calendar views 
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/147500462/421b99ad-d406-4c96-89cd-f95b12fd71db) 
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/147500462/f39285bd-773d-4fc4-9f15-5d6dcf20e4d6) 
|
=> VFB-39-Specify visible time period for calendar

src/app/clients/ClientParcelsTable.tsx, src/app/clients/ClientsPage.tsx, src/app/parcels/ParcelsPage.tsx, src/components/Tables/Table.tsx
- Add highlight on hover
- Add pointer on hover for parcels, clients, client detail modal tables
- Parcels table checkbox cell on click does not trigger opening of modal
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/ad0b5474-9713-461f-90aa-105d6c5ea45f) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/84ae980c-70a7-4ab7-ab57-8c747a7663b9) |
=> VFB-114: Table row styling

.github/workflows/deploy-dev-edge-functions.yml, .github/workflows/deploy-prod-edge-functions.yml
Auto-deploy edge functions 
- to dev Supabse on merge / push to dev branch
- to prod Supabase on merge / push to main branch, with approval
I've also test-run the deployment to dev supabase. The deployment was successful and the dev website seems to be working okay.
=> VFB-109: Auto deploy edge functions

src/app/lists/ListDataview.tsx, src/app/parcels/ParcelsPage.tsx, src/app/parcels/fetchParcelTableData.ts
=> VFB-57-fix-dev-deploy

src/logger/logger.ts
REPLACE_THIS_LINE
| <img width="168" alt="image" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/114006382/7c4e128e-bdef-4478-b851-e844350a5e55"> | <img width="1086" alt="image" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/114006382/8a3f0e82-207a-4693-81d9-ca2a82401f29"> |
=> VFB-57-fix: Log error ID and metadata correctly

.github/workflows/checks.yml, README.md, docs/README.md, docs/password-reset-flow.md
Add password reset sequence diagram
=> NONE: Add password reset diagram

src/app/parcels/ParcelsPage.cy.tsx, src/databaseTypesFile.ts
We have forgotten to update the database type file in https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/actions/runs/8439814805
=> NONE: Update database type file

docs/README.md, docs/supabase-realtime-reset.md
Add tables that need realtime turned on in docs
=> NONE-add-realtime-reset-doc

src/components/Form/formFunctions.ts
It is now possible to add a new parcel with the packing date set to today.
|![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/4223620e-e864-4b9f-b78a-3fd377dd1670)|![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/af38239f-71a3-40c0-9091-864a06460e4b)|
No DB changes
=> #179: Allow adding a parcel with packing date set to today

.github/pull_request_template.md
Update PR template to test for db migration locally
=> NONE: Update PR template to test for db migration locally

.snaplet/snaplet-client.d.ts, .snaplet/snaplet.d.ts, src/app/parcels/form/clientDatabaseFunctions.ts, src/databaseTypesFile.ts, src/server/auditLog.ts, src/server/getCurrentUser.ts, supabase/migrations/20240405104731_add_audit_log_table.sql
Add audit logging when parcels are added or edited
- [N/A] I have modified the seed in `supabase/seed/seed.mts` if appropriate
- [N/A ] If I have modified the seed, I have also generated the seed with `npm run db:generate_seed` 
- Does this require resetting the deployed database? - YES (remove as appropriate)
- Check that the resulting database is what you …
=> VFB-173: Set up audit logging and log changes when parcel is added or edited

supabase/config.toml, supabase/templates/invite.html, supabase/templates/recovery.html
Include email templates in git history.
=> NONE: Include email templates in git history

.github/pull_request_template.md
last line of PR template:
- Check that the resulting database is what you expect.
is now
=> NONE: Update PR template

package.json
Changed command test:e2e in package.json
=> NONE: Fix test:e2e command

src/app/admin/common/SuccessFailureAlert.tsx, src/app/admin/createUser/CreateUserForm.tsx, src/app/admin/deleteUser/DeleteUserDialog.tsx, src/app/admin/usersTable/UsersTable.tsx, src/server/adminDeleteUser.ts, src/server/adminInviteUser.ts, supabase/migrations/20240416083736_enable_realtime_for_profiles_table.sql
- Add audit log when user is deleted
=> VFB-197: Add audit log to delete user action

src/app/parcels/form/ParcelForm.tsx, src/app/parcels/form/formSections/VoucherNumberCard.tsx
Make voucher number not required.
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/114006382/3d933c75-92d1-47e8-be09-6fc9c038366a) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/114006382/f2343c59-08a8-4ebc-be14-7e5bd312f36c) |
If you have made any changes to the database... Nope
- Check that …
=> #204: Make voucher number not required

.github/workflows/dump-dev-database.yml, README.md, docs/disaster-recovery-plan.md
Add disaster recovery docs and workflow to back up database every hour
=> VFB-79: Add disaster recovery docs and workflow to back up database every hour

package-lock.json
=> NONE: Security updates

src/app/parcels/ActionBar/ActionModals/ShoppingListModal.tsx, src/pdf/FontAwesomeIconPdfComponent.tsx, src/pdf/ShippingLabels/ShippingLabelsPdf.tsx, src/pdf/ShoppingList/ShoppingListPdf.tsx, src/pdf/ShoppingList/getShoppingListData.ts, src/pdf/ShoppingList/shoppingListPdfDataProps.ts
- Matching formatting of shopping list with existing shopping list
- Add truck or building icon depending on delivery or collection on shopping list and shipping labels (absorbed [VFB-56](https://softwiretech.atlassian.net/jira/software/c/projects/VFB/boards/862?selectedIssue=VFB-56))
- Fix bug for notes and quantity not showing in pdf
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/c2f9ea63-76ef-402b-a8b7-7225c3ed2d25) ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/5c8ac738-9bed-4726-baf2-dc9c8fa7a921) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/f31dd36c-111f-4733-b804-2e54cca241f1) …
=> VFB-62: Edit shopping list pdf to match old layout

cypress/e2e/accessibility.cy.ts, src/app/clients/ClientParcelsTable.tsx, src/app/parcels/ParcelsPage.tsx, src/app/parcels/getExpandedParcelDetails.ts, src/app/parcels/parcelsTableFilters.ts
- Rename collection columns to method in parcels table column, filter, parcels modal and clients modal parcels table column
- Display flagged for attention and follow up icons in parcels table as default
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/873c6671-e8de-4c88-821a-39076c631cbb) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/ebc166e3-8384-4daf-a0a6-500c6be4c192) |
- Run `npm run post_checkout` to reset the …
=> VFB-140 Rename collection to method for parcels

src/app/parcels/ActionBar/Actions.tsx
- Reordered actions in the actions drop-down menu on the parcels page
|![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167985277/9bb6c33a-b3c7-49f4-8470-612be7bd6505)|![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167985277/f61f4ff8-8bff-48ee-8cdc-70e8c60a4947)|
If you have made any changes to the database... (no changes made)
=> #245: Reordered actions in parcel page

.github/workflows/dump-prod-database.yml
=> VFB-215: Encrypt db backup

docs/disaster-recovery-plan.md
Update disaster recovery docs on backup decryption
=> VFB-215: Update disaster recovery docs on backup decryption

README.md
Add port exclusion instructions to README
=> Add port exclusion instructions to README
